Update flags, update readme
- Remove -v flag - we see current version with -i/--installed
- Add -s as short flag for --select
- Add GCLV_BINARIES_DIR to set where binaries are installed
- Add GCLV_BINARY_DIR to set where to symlink selected version
- Fix typo in variable names
- Update readme with a v2 example as first example
- Fix typos in readme
- Change prompt in readme

diff --git a/gclv b/gclv
--- a/gclv
+++ b/gclv
@@ -6,35 +6,38 @@ should_run=
 version=
 to_remove=
 golangci_lint_config_yaml=
-golangci_binaries_dir=$HOME/.golangci-lint
-golangci_binary_dir=$HOME/bin
+golangci_binaries_dir=${GCLV_BINARIES_DIR:-$HOME/.golangci-lint}
+golangci_binary_dir=${GCLV_BINARY_DIR:-$HOME/bin}
 current_version_file="$golangci_binaries_dir/.version"
 
 __usage() {
-  echo "gclv - goalngci-lint version"
+  echo "gclv - golangci-lint version"
   echo ""
   echo "Select which version of golangci-lint to use. If a configuration YAML"
-  echo "file is specified the version will be derived from ther."
+  echo "file is specified the version will be derived from there."
   echo ""
-  echo "  -h | --help          | Print this help"
-  echo "  -v | --version       | Print the currently selected version"
-  echo "  -i | --installed     | Print all installed versions"
-  echo "  --select <version>   | Select a version to use."
-  echo "                       |   Will download version if not found locally."
-  echo "                       |   Set to 'latest' to download latest version"
-  echo "  --from-config <file> | Select a version to use from golangci-lint config."
-  echo "                       |   Will download version if not found locally."
-  echo "  --remove <version>   | Remove an installed version."
-  echo "  --run                | Run golangci-lint after chaning version from config."
-  echo "  --binary-dir         | Where to link golangci-lint binary."
-  echo "                       |  Default $HOME/bin."
+  echo "Download location can be set with GCLV_BINARIES_DIR."
+  echo "Default $HOME/.golangci-lint."
+  echo ""
+  echo "  -h | --help              |  Print this help"
+  echo "  -i | --installed         |  Print installed versions and currently selected version"
+  echo "  -s | --select <version>  |  Select a version to use."
+  echo "                           |    Will download version if not found locally."
+  echo "                           |    Set to 'latest' to download latest version"
+  echo "  --from-config <file>     |  Select a version to use from golangci-lint config."
+  echo "                           |    Will download version if not found locally."
+  echo "  --remove <version>       |  Remove an installed version."
+  echo "  --run                    |  Run golangci-lint after changing version from config."
+  echo "  --binary-dir             |  Where to link golangci-lint binary."
+  echo "                           |   Can be set via GCLV_BINARY_DIR"
+  echo "                           |   Default $HOME/bin."
 
   exit 0
 }
 
 __get_version_from_config() {
   if [ ! -f "$golangci_lint_config_yaml" ]; then
-    echo >&2 "'$golangci_lint_config_yaml' was not found - chose an existing file"
+    echo >&2 "'$golangci_lint_config_yaml' was not found - choose an existing file"
     exit 1
   fi
 
@@ -115,9 +118,9 @@ __remove_binary() {
 }
 
 __set_golangci_yaml_from_arguments() {
-  argumnets_length=$#
+  arguments_length=$#
   # Iterate over all remaining arguments to see if we find the `--config` flag.
-  for ((i = 1; i <= "$argumnets_length"; i++)); do
+  for ((i = 1; i <= "$arguments_length"; i++)); do
     case "${!i}" in
     # Check if the argument starts with `--config`.
     --config*)
@@ -161,14 +164,10 @@ while test $# -gt 0; do
   -h | --help)
     __usage
     ;;
-  -v | --version)
-    __get_current_version
-    exit 0
-    ;;
   -i | --installed)
     __print_installed
     ;;
-  --select*)
+  -s | --select*)
     if [ "${1/=/}" = "$1" ]; then
       shift
     fi
